name: Publish (PyPI/TestPyPI)

on:
  # Manual trigger lets you choose where to publish
  workflow_dispatch:
    inputs:
      target:
        description: "Publish target"
        required: true
        type: choice
        options: [testpypi, pypi]
        default: testpypi
  # Automatic publish on GitHub Release
  release:
    types: [published]

jobs:
  build:
    name: Build distribution
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip

      - name: Install build backend
        run: python -m pip install --upgrade pip build

      - name: Build sdist and wheel
        run: python -m build

      - name: Upload dist artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  publish-testpypi:
    name: Publish to TestPyPI
    needs: build
    if: ${{ github.event_name == 'workflow_dispatch' && inputs.target == 'testpypi' }}
    runs-on: ubuntu-latest
    environment: testpypi   # <- create this Environment in Settings → Environments
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/
      - name: Publish package (TestPyPI)
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}

  publish-pypi:
    name: Publish to PyPI
    needs: build
    # Either manual dispatch with target=pypi, or auto on Release
    if: ${{ (github.event_name == 'workflow_dispatch' && inputs.target == 'pypi') || github.event_name == 'release' }}
    runs-on: ubuntu-latest
    environment: pypi       # <- create this Environment in Settings → Environments
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/
      - name: Publish package (PyPI)
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
