name: Publish (PyPI/TestPyPI)

on:
  workflow_dispatch:
    inputs:
      target:
        description: "Publish target"
        required: true
        type: choice
        options: [testpypi, pypi]
        default: testpypi
  release:
    types: [published]

permissions:
  contents: read
  id-token: write   # REQUIRED for Trusted Publisher (OIDC)

jobs:
  build:
    name: Build distribution
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip

      - name: Install build backend
        run: python -m pip install --upgrade pip build

      - name: Build sdist and wheel
        run: python -m build

      - name: Upload dist artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  publish-testpypi:
    name: Publish to TestPyPI (OIDC)
    needs: build
    # Run when manually selected "testpypi"
    if: ${{ github.event_name == 'workflow_dispatch' && inputs.target == 'testpypi' }}
    runs-on: ubuntu-latest
    environment: testpypi      # create in Settings → Environments (optional but recommended)
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      # No username/password here. OIDC is used automatically.
      - name: Publish package to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          verbose: true

  publish-pypi:
    name: Publish to PyPI (OIDC)
    needs: build
    # Run when manually selected "pypi", or automatically on Release publish
    if: ${{ (github.event_name == 'workflow_dispatch' && inputs.target == 'pypi') || github.event_name == 'release' }}
    runs-on: ubuntu-latest
    environment: pypi          # create in Settings → Environments (optional but recommended)
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      # No username/password here. OIDC is used automatically.
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true